import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  developerNotesSidebar: [
    'developer-notes',
    {
      type: 'category',
      label: 'Roadmap',
      link: {
        type: 'generated-index',
        title: 'Roadmap',
        description: 'Phase plans and project roadmap documents.',
      },
      items: [{type: 'autogenerated', dirName: 'roadmap'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture',
        description: 'Cross-cutting design and process guidance.',
      },
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Implementation',
      link: {
        type: 'generated-index',
        title: 'Implementation',
        description: 'Revision-by-revision implementation notes.',
      },
      items: [{type: 'autogenerated', dirName: 'implementation'}],
    },
  ],
};

export default sidebars;
